spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/students_db
    username: cuba
    password: cuba
  driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update